apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprormq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vprormq
  template:
    metadata:
      labels:
        app: vprormq
    spec:
      containers:
       - name: vprormq
         image: rabbitmq
         ports:
          - containerPort: 5672
            name: vprormq-port
         env:
          - name: RABBITMQ_DEFAULT_PASSWORD
            valueFrom:
              secretKeyRef:
               name: app-secret
               key: rmq-pass
          - name : RABBITMQ_DEFAULT_USER
            value: "guest"

